# Default values for maestro-addon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageOverrides:
    maestroImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/maestro-main/maestro-main:8c93e2e652a317c7335665a7022a325e9efb58fe
    maestroAddOnImage: quay.io/skeeey/maestro-addon:latest
    postgresImage: quay.io/maestro/postgres:17.2
  imagePullPolicy: IfNotPresent
  pullSecret: ""
  namespace: maestro

maestro:
  replicas: 1
  logLevel: 2
  broker: grpc # kafka

maestroAgent:
  logLevel: 2

addOnManager:
  namespace: open-cluster-management-hub

maestroAddOn:
  logLevel: 2

database:
  useExternalDB: false
  storage: 1Gi

messageQueue:
  amqStreams:
    name: "kafka"
    namespace: "amq-streams"
    listener:
      type: "route"
      port: 443
  grpc:
    type: "route"
