apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maestro
    template: maestro
  name: maestro
  namespace: '{{ .Values.global.namespace }}'
spec:
  replicas: {{ .Values.maestro.replicas }}
  selector:
    matchLabels:
      app: maestro
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maestro
    spec:
      containers:
      - command:
        - "/usr/local/bin/maestro"
        - server
        - "--client-id=maestro-$(POD_NAME)"
        - "--message-broker-type={{ .Values.maestro.broker }}"
{{- if eq .Values.maestro.broker "kafka" }}
        - "--message-broker-config-file=/secrets/mq/kafka/config.yaml"
{{- end }}
        - "--db-host-file=/secrets/rds/host"
        - "--db-port-file=/secrets/rds/port"
        - "--db-user-file=/secrets/rds/user"
        - "--db-password-file=/secrets/rds/password"
        - "--db-name-file=/secrets/rds/name"
        - "--db-sslmode=disable"
        - "--db-max-open-connections=50"
        - "--server-hostname=0.0.0.0"
        - "--enable-ocm-mock=true"
        - "--enable-jwt=false"
        - "--enable-sentry=false"
        - "--http-server-bindport=8000"
        - "--http-read-timeout=5s"
        - "--http-write-timeout=30s"
        - "--enable-grpc-server=true"
        - "--grpc-server-bindport=8090"
{{- if eq .Values.maestro.broker "grpc" }}
        - "--grpc-broker-bindport=8091"
        - "--grpc-broker-client-ca-file=/secrets/certs/grpc-broker/ca.crt"
        - "--grpc-broker-tls-cert-file=/secrets/certs/grpc-broker/server.crt"
        - "--grpc-broker-tls-key-file=/secrets/certs/grpc-broker/server.key"
{{- end }}
        - "--alsologtostderr"
        - "-v={{ .Values.maestro.logLevel }}"
        env:
        - name: AMS_ENV
          value: development
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.global.imageOverrides.maestroImage }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: http-port
          containerPort: 8000
        - name: grpc-port
          containerPort: 8090
        - name: readiness-port
          containerPort: 8083
        livenessProbe:
          httpGet:
            path: "/api/maestro"
            port: http-port
          initialDelaySeconds: 15
          periodSeconds: 5
        name: service
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: User-Agent
              value: Probe
            path: "/healthcheck"
            port: readiness-port
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: "/secrets/rds"
          name: maestro-db-config
{{- if eq .Values.maestro.broker "grpc" }}
        - mountPath: "/secrets/certs/grpc-broker"
          name: grpc-broker-certs
{{- end }}
{{- if eq .Values.maestro.broker "kafka" }}
        - mountPath: "/secrets/certs/kafka"
          name: kafka-client-certs
        - mountPath: "/secrets/mq/kafka"
          name: maestro-kafka-config
{{- end }}
      initContainers:
      - command:
        - "/usr/local/bin/maestro"
        - migration
        - "--db-host-file=/secrets/rds/host"
        - "--db-port-file=/secrets/rds/port"
        - "--db-user-file=/secrets/rds/user"
        - "--db-password-file=/secrets/rds/password"
        - "--db-name-file=/secrets/rds/name"
        - "--alsologtostderr"
        - "-v={{ .Values.maestro.logLevel }}"
        image: {{ .Values.global.imageOverrides.maestroImage }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: migration
        volumeMounts:
        - mountPath: "/secrets/rds"
          name: maestro-db-config
      serviceAccountName: maestro
      volumes:
      - name: maestro-db-config
        secret:
          secretName: maestro-db-config
{{- if eq .Values.maestro.broker "kafka" }}
      - name: maestro-kafka-config
        secret:
          secretName: maestro-kafka-config
      - name: kafka-client-certs
        secret:
          secretName: kafka-client-certs
{{- end }}
{{- if eq .Values.maestro.broker "grpc" }}
      - name: grpc-broker-certs
        secret:
          secretName: grpc-broker-certs
{{- end }}
